# Generated by Django 4.2.7 on 2023-11-23 08:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("social_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 23, 8, 38, 11, 632216, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="joined_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
