# Generated by Django 4.2.7 on 2023-11-23 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_app", "0004_alter_post_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="posts",
        ),
    ]
