# Generated by Django 4.2.7 on 2023-11-23 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_app", "0005_alter_post_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"], "verbose_name": "User Post"},
        ),
    ]
